### ISSUE TITLE
Distinguish the JSON (i.e. Machine Actionable) output and other (textual) output in the picture.

### ISSUE THREAD

**Issue by roper79** [ds-wizard/dsw-leaflet#2]

**Comment by MarekSuchanek** [comment]
Updated in https://github.com/DataStewardshipWizard/dsw-leaflet/pull/1/commits/ee69e53f8ff01c0d15ba5901a9c4820288bd1d17, please take a look @perglr

**Comment by roper79** [comment]
What is profit? Sounds weird here ;-)

**Comment by MarekSuchanek** [comment]
True... some people could think that we will give them money 😄 So something like "Benefits" or "Success"? Or nothing?

**Comment by roper79** [comment]
Still sounds like a marketing bullshit... I would leave this out entirely ;-)
