### ISSUE TITLE
Use Travis + ImageMagic to generate PDF

### ISSUE THREAD

**Issue by roper79** [ds-wizard/dsw-leaflet#4]

**Comment by MarekSuchanek** [comment]
Where should be the resulting PDF placed?

**Comment by roper79** [comment]
Right now, I would just put it in the root...

This issue is not urgent, just a cool idea (that does not pay back so much here :-)

**Comment by MarekSuchanek** [comment]
OK, I will do this now since we need new leaflet... 

1. No PDF in the repository - it will only cause inconsistency.
2. Only releases will have the PDF
3. PDF to release can be uploaded automatically from Travis and include tag in filename
4. DOI from Zenodo will make it citable - via releases

**Comment by MarekSuchanek** [comment]
Finished, now I can work on version `v2.0.0`
